### ISSUE TITLE
make the test programmable map reduce run in Python 3

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#207]
failing to convert some object at `./python//teca_py_data.i:431`

```
pipin:~/TECA/bin$ctest -R py_ -I 12,12,1 --verbose
UpdateCTestConfiguration  from :/Users/bloring/TECA/bin/DartConfiguration.tcl
Parse Config file:/Users/bloring/TECA/bin/DartConfiguration.tcl
 Add coverage exclude regular expressions.
SetCTestConfiguration:CMakeCommand:/usr/local/Cellar/cmake/3.13.3/bin/cmake
UpdateCTestConfiguration  from :/Users/bloring/TECA/bin/DartConfiguration.tcl
Parse Config file:/Users/bloring/TECA/bin/DartConfiguration.tcl
Test project /Users/bloring/TECA/bin
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 60
    Start 60: py_test_programmable_map_reduce_serial

60: Test command: /usr/local/bin/python3 "/Users/bloring/TECA/test/python/test_programmable_map_reduce.py" "/Users/bloring/TECA/../TECA_data/cam5_1_amip_run2\.cam2\.h2\.1991-10-0[12]-10800\.nc" "/Users/bloring/TECA/../TECA_data/py_test_programmable_map_reduce.bin" "0" "-1" "1" "TMQ" "T200" "T500"
60: Test timeout computed to be: 1500
60: WARNING: [0:0x1034fe5c0] [/Users/bloring/TECA/core/teca_thread_pool.h:112 2.2.1-54-g2dcb7fc]
60: WARNING: Cannot autmatically detect threading parameters on this platform. The default is 1 thread per process.
60: ERROR: [0:0x70000b51e000] [/Users/bloring/TECA/python/teca_py_algorithm.h:263 2.2.1-54-g2dcb7fc]
60: ERROR: An exception ocurred when invoking the user supplied Python callback "<function get_execute_callback.<locals>.execute at 0x103693d90>"for the execute execution phase. The exception that occurred is:
60: ERROR: [0:0x70000b51e000] [/Users/bloring/TECA/python/teca_py_algorithm.h:263 2.2.1-54-g2dcb7fc]
60: ERROR: An exception ocurred when invoking the user supplied Python callback "<function get_execute_callback.<locals>.execute at 0x103693d90>"for the execute execution phase. The exception that occurred is:
60: ERROR: [0:0x70000b51e000] [/Users/bloring/TECA/python/teca_py_algorithm.h:263 2.2.1-54-g2dcb7fc]
60: ERROR: An exception ocurred when invoking the user supplied Python callback "<function get_execute_callback.<locals>.execute at 0x103693d90>"for the execute execution phase. The exception that occurred is:
60: ERROR: [0:0x70000b51e000] [/Users/bloring/TECA/python/teca_py_algorithm.h:263 2.2.1-54-g2dcb7fc]
60: ERROR: An exception ocurred when invoking the user supplied Python callback "<function get_execute_callback.<locals>.execute at 0x103693d90>"for the execute execution phase. The exception that occurred is:
60: ERROR: [0:0x1034fe5c0] [/Users/bloring/TECA/alg/teca_table_sort.cxx:120 2.2.1-54-g2dcb7fc]
60: ERROR: empty input
60: ERROR: [0:0x1034fe5c0] [/Users/bloring/TECA/alg/teca_table_calendar.cxx:126 2.2.1-54-g2dcb7fc]
60: ERROR: Input is empty or not a table
60: ERROR: [0:0x1034fe5c0] [/Users/bloring/TECA/alg/teca_dataset_diff.cxx:90 2.2.1-54-g2dcb7fc]
60: ERROR: Input dataset 2 is NULL.
60: Testing on 1 MPI processes 1 threads
60: [0] execute
60: TypeError: failed to append object
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 10508, in <lambda>
60:     __setattr__ = lambda self, name, value: _swig_setattr(self, teca_table, name, value)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 90, in _swig_setattr
60:     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 74, in _swig_setattr_nondynamic
60:     if type(value).__name__ == 'SwigPyObject':
60: SystemError: <class 'type'> returned a result with an error set
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/test/python/test_programmable_map_reduce.py", line 57, in execute
60:     << map(float, np.percentile(var, [25.,50.,75.]))
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 11090, in __lshift__
60:     return _teca_py.teca_table___lshift__(self, obj)
60: SystemError: <built-in function teca_table___lshift__> returned a result with an error set
60: [0] execute
60: TypeError: failed to append object
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 10508, in <lambda>
60:     __setattr__ = lambda self, name, value: _swig_setattr(self, teca_table, name, value)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 90, in _swig_setattr
60:     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 74, in _swig_setattr_nondynamic
60:     if type(value).__name__ == 'SwigPyObject':
60: SystemError: <class 'type'> returned a result with an error set
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/test/python/test_programmable_map_reduce.py", line 57, in execute
60:     << map(float, np.percentile(var, [25.,50.,75.]))
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 11090, in __lshift__
60:     return _teca_py.teca_table___lshift__(self, obj)
60: SystemError: <built-in function teca_table___lshift__> returned a result with an error set
60: [0] execute
60: TypeError: failed to append object
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 10508, in <lambda>
60:     __setattr__ = lambda self, name, value: _swig_setattr(self, teca_table, name, value)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 90, in _swig_setattr
60:     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 74, in _swig_setattr_nondynamic
60:     if type(value).__name__ == 'SwigPyObject':
60: SystemError: <class 'type'> returned a result with an error set
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/test/python/test_programmable_map_reduce.py", line 57, in execute
60:     << map(float, np.percentile(var, [25.,50.,75.]))
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 11090, in __lshift__
60:     return _teca_py.teca_table___lshift__(self, obj)
60: SystemError: <built-in function teca_table___lshift__> returned a result with an error set
60: [0] execute
60: TypeError: failed to append object
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 10508, in <lambda>
60:     __setattr__ = lambda self, name, value: _swig_setattr(self, teca_table, name, value)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 90, in _swig_setattr
60:     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 74, in _swig_setattr_nondynamic
60:     if type(value).__name__ == 'SwigPyObject':
60: SystemError: <class 'type'> returned a result with an error set
60: 
60: The above exception was the direct cause of the following exception:
60: 
60: Traceback (most recent call last):
60:   File "/Users/bloring/TECA/test/python/test_programmable_map_reduce.py", line 57, in execute
60:     << map(float, np.percentile(var, [25.,50.,75.]))
60:   File "/Users/bloring/TECA/bin/lib/teca_py.py", line 11090, in __lshift__
60:     return _teca_py.teca_table___lshift__(self, obj)
60: SystemError: <built-in function teca_table___lshift__> returned a result with an error set
60: [0] reduce
60: [0] reduce
60: [0] reduce
1/1 Test #60: py_test_programmable_map_reduce_serial ...***Failed  Error regular expression found in output. Regex=[ERROR]  0.36 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.38 sec

The following tests FAILED:
	 60 - py_test_programmable_map_reduce_serial (Failed)
Errors while running CTest
```

**Comment by burlen** [comment]
see also #165, #205, #206

**Comment by burlen** [comment]
The behaavior of maps changed in Python 3. The problematic line is
```
 55             table << float(np.min(var)) << float(np.average(var)) \
 56                 << float(np.max(var)) << float(np.std(var)) \
 57                 << map(float, np.percentile(var, [25.,50.,75.]))
```
where the last lshift now is passed as an iteratable object, rather than an explicit list. We can work around it by wrapping it like so `list(map(...))`. That works for both 2 and 3. 

The real solution is to support consuming iterators. https://docs.python.org/3/c-api/iter.html


```
PyObject *iterator = PyObject_GetIter(obj);
PyObject *item;

if (iterator == NULL) {
    /* propagate error */
}

while (item = PyIter_Next(iterator)) {
    /* do something with item */
    ...
    /* release reference when done */
    Py_DECREF(item);
}

Py_DECREF(iterator);

if (PyErr_Occurred()) {
    /* propagate error */
}
else {
    /* continue doing useful work */
}
```

**Comment by burlen** [comment]
work around in #203
