### ISSUE TITLE
python bindings don't work after pip or setup.py install

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#213]
When installing TECA via setup.py (either using pip or `python setup.py install`), the python bindings don't appear to be installed properly:

```bash
$ python -c 'import teca; test = teca.teca_cf_reader.New()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'teca' has no attribute 'teca_cf_reader'
$ python -c 'import teca; help(teca)'
Help on module teca:

NAME
    teca

FILE
    /opt/conda/lib/python3.7/site-packages/teca.py
```

This appears to be because `teca.py` contains
```python
import sys, os
from teca import *
```
The `from teca ...` line is self-referential to `teca.py`, which is likely why it imports nothing(Also, the TECA files were installed directly in the site-packages folder, rather than a teca subfolder, which seems odd.)

In contrast, when TECA is installed directly via CMAKE, the `teca.py` file contains
`from teca_py import *`.

However, if I modify the installed `teca.py` to import from `teca_py` instead, a shared library error results:

```bash
$ python -c 'import teca; test = teca.teca_cf_reader.New()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/teca.py", line 2, in <module>
    from teca_py import *
  File "/opt/conda/lib/python3.7/site-packages/teca_py.py", line 33, in <module>
    import _teca_py
ImportError: libteca_alg.so: cannot open shared object file: No such file or directory
```

If I set `LD_LIBRARY_PATH` accordingly (but see note below), I get a new error:
```bash
$ python -c 'import teca; test = teca.teca_cf_reader.New()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/teca.py", line 2, in <module>
    from teca_py import *
  File "/opt/conda/lib/python3.7/site-packages/teca_py.py", line 12140, in <module>
    from teca_tc_stats import *
ModuleNotFoundError: No module named 'teca_tc_stats'
```

This import error occurs because the install resulted in `teca_tc_stats.py` being installed in `/.../site-packages/lib`.  If I set `PYTHONPATH` accordingly, the `python -c 'import teca; test = teca.teca_cf_reader.New()'` command then works as expected.

**Thoughts:**

The path issue should be easy to fix by modifying how/where setup.py puts files, so a user shouldn't need to set PYTHONPATH.

The library path is a bit trickier.  I believe this could be solved w/o needing LD_LIBRARY_PATH by setting the rpath of the shared libraries, but this would require knowing the final install location at build time (or modifying it post-install?).  There must be a way to do this with distutils, since Cython-based shared libraries install via setup.py without issue.  I don't know how though, and I'm not sure how this would work with cmake in the mix.

**Comment by taobrienlbl** [comment]
@burlen - could you please confirm here whether you can replicate the above issues after a setup.py install?
