### ISSUE TITLE
some minor teca_pytorch issues

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#342]
@elbashandy -- nice work on getting the TECA CNN model going!  I just ran a successful test (once I got passed my DAUE build issues that you, @burlen, and I discussed on our call).

I've encountered a few minor issues:

1. trying to print the help by using the `-h` or `--help` flags results in odd behavior (see below)
2. `sys.stdout.write` is used in `teca_model_segmentation.py` (line 139), but `sys` is not imported
3. IVT shouldn't be included in the output files
4. let's change the name of the output variable from `IVT_pred` to `ar_probability`, and it should have the following metadata

```
	float ar_probability(time, lat, lon) ;
		ar_probability:long_name = "estimated AR probability" ;
		ar_probability:units = "probability" ;
```

For 1., here is the output:
```
Traceback (most recent call last):
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/bin/teca_pytorch_deeplabv3p_ar_detect", line 246, in <module>
    main()
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/bin/teca_pytorch_deeplabv3p_ar_detect", line 103, in main
    args = parser.parse_args()
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 1037, in __call__
    parser.print_help()
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 2474, in print_help
    self._print_message(self.format_help(), file)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 2458, in format_help
    return formatter.format_help()
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 525, in _format_action
    help_text = self._expand_help(action)
  File "/global/common/software/m1517/users/taobrien/TECA_superbuild/install_haswell_develop/lib/python3.7/argparse.py", line 614, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character 't' (0x74) at index 39
```

**Comment by burlen** [comment]
@elbashandy  we hit 1. during one of our debug sessions, it is because of the use of the character '%' in the help string. The solution is to replace '%' with '%%'.

Two more issues I see:
5. need to make the application executable, run `chmod 755` on it, then commit.
6. remove 'pytorch' from the app name
